import Navbar from '@/Components/shared/Navbar'
import './globals.css'
import Footer from '@/Components/shared/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='max-w-[1350px] mx-auto'>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
